<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <DefineConstants>XenoKit</DefineConstants>
    <RootNamespace>XenoKit</RootNamespace>
    <AssemblyName>XenoKit</AssemblyName>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>XenoKitIcon.ico</ApplicationIcon>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
	
	<!-- NuGet package references -->
	<ItemGroup>
		<PackageReference Include="CommonServiceLocator" Version="2.0.2" />
		<PackageReference Include="ControlzEx" Version="4.4.0" />
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
		<PackageReference Include="Cyotek.Drawing.BitmapFont" Version="2.0.4" />
		<PackageReference Include="FontStashSharp.Base" Version="1.2.8" />
		<PackageReference Include="FontStashSharp.MonoGame" Version="1.5.8" />
		<PackageReference Include="FontStashSharp.Rasterizers.StbTrueTypeSharp" Version="1.2.8" />
    <PackageReference Include="MvvmLightStd10" Version="5.4.1.2" />
		<PackageReference Include="gong-wpf-dragdrop" Version="3.2.0" />
		<PackageReference Include="MahApps.Metro" Version="2.4.10" />
		<PackageReference Include="MahApps.Metro.IconPacks.Core" Version="6.0.0" />
		<PackageReference Include="MahApps.Metro.IconPacks.Lucide" Version="6.0.0" />
		<PackageReference Include="MahApps.Metro.IconPacks.Material" Version="4.11.0" />
		<PackageReference Include="MahApps.Metro.IconPacks.MaterialDesign" Version="4.11.0" />
		<PackageReference Include="MahApps.Metro.IconPacks.MaterialLight" Version="4.11.0" />
		<PackageReference Include="MahApps.Metro.IconPacks.Modern" Version="4.11.0" />
		<PackageReference Include="MIConvexHull" Version="1.1.19.1019" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.19" />
		<PackageReference Include="NAudio" Version="1.9.0" />
		<PackageReference Include="Ookii.Dialogs.Wpf" Version="1.1.0" />
		<PackageReference Include="Pfim" Version="0.11.3" />
		<PackageReference Include="SharpDX" Version="4.2.0" />
		<PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
		<PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
		<PackageReference Include="StbImageSharp" Version="2.30.16" />
		<PackageReference Include="StbTrueTypeSharp" Version="1.26.13" />
		<PackageReference Include="System.Buffers" Version="4.6.1" />
		<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="10.0.11" />
		<PackageReference Include="System.IO" Version="4.3.0" />
		<PackageReference Include="System.Linq" Version="4.3.0" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
		<PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
		<PackageReference Include="System.Reflection" Version="4.3.0" />
		<PackageReference Include="System.Runtime" Version="4.3.1" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
		<PackageReference Include="System.Runtime.Extensions" Version="4.3.1" />
		<PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
		<PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
		<PackageReference Include="WriteableBitmapEx" Version="1.6.11" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="AutoUpdater">
			<HintPath>..\..\XV2 Tools\DLLs\AutoUpdater.dll</HintPath>
		</Reference>
		<Reference Include="System.Half">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>..\..\XV2 Tools\DLLs\System.Half.dll</HintPath>
		</Reference>
		<Reference Include="YAXLib">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>..\..\XV2 Tools\DLLs\YAXLib.dll</HintPath>
		</Reference>

		<Reference Include="System" />
		<Reference Include="System.ComponentModel.Composition" />
		<Reference Include="System.Numerics" />
		<Reference Include="System.Xaml" />
		<Reference Include="WindowsBase" />
		<Reference Include="PresentationCore" />
		<Reference Include="PresentationFramework" />
		<Reference Include="PresentationFramework.Aero" />
	</ItemGroup>
	
  <ItemGroup>
    <Resource Include="Resources\transparent_checkerboard.png" />
  </ItemGroup>
	
	<!-- Linked references to EEPK Editor and ACE -->
	<ItemGroup>
		<Compile Include="..\..\XV2 Tools\AudioCueEditor\Audio\AudioFormat.cs">
      <Link>Views\ACE\Audio\AudioFormat.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\Audio\AudioPlayer.cs">
      <Link>Views\ACE\Audio\AudioPlayer.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\Audio\Helper.cs">
      <Link>Views\ACE\Audio\Helper.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\Audio\LoopStream.cs">
      <Link>Views\ACE\Audio\LoopStream.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\Audio\WavStream.cs">
      <Link>Views\ACE\Audio\WavStream.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\Data\HcaEncryptionKeys.cs">
      <Link>Views\ACE\Data\HcaEncryptionKeys.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\ViewModel\MainViewModel.cs">
      <Link>Views\ACE\ViewModel\MainViewModel.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\ViewModel\ViewModelLocator.cs">
      <Link>Views\ACE\ViewModel\ViewModelLocator.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\View\AddCueForm.xaml.cs">
      <Link>Views\ACE\View\AddCueForm.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\View\AddTrackForm.xaml.cs">
      <Link>Views\ACE\View\AddTrackForm.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\View\CueEditorView.xaml.cs">
      <Link>Views\ACE\View\CueEditorView.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\View\EditCueLimit.xaml.cs">
      <Link>Views\ACE\View\EditCueLimit.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\View\EditLoopForm.xaml.cs">
      <Link>Views\ACE\View\EditLoopForm.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\View\EditVolume.xaml.cs">
      <Link>Views\ACE\View\EditVolume.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\AudioCueEditor\View\VolumeControl.xaml.cs">
      <Link>Views\ACE\View\VolumeControl.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\AssetContainerSettings.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\AssetContainerSettings.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\AssetSelector.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\AssetSelector.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\Editors\EcfEditorWindow.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\Editors\EcfEditorWindow.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\Editors\EmbEditForm.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\Editors\EmbEditForm.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\Editors\EmpEditorWindow.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\Editors\EmpEditorWindow.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\Editors\EtrEditorWindow.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\Editors\EtrEditorWindow.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\Editors\MaterialsEditorForm.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\Editors\MaterialsEditorForm.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\EffectSelector.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\EffectSelector.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\EntitySelector.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\EntitySelector.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\KeyframeScale.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\KeyframeScale.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\Recolor\RecolorAll.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\Recolor\RecolorAll.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\Recolor\RecolorTexture.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\Recolor\RecolorTexture.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Forms\RenameForm.xaml.cs">
      <Link>Views\EEPK Organiser\Forms\RenameForm.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Misc\CacheManager.cs">
      <Link>Views\EEPK Organiser\Misc\CacheManager.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Misc\ClipboardDataTypes.cs">
      <Link>Views\EEPK Organiser\Misc\ClipboardDataTypes.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\Misc\LoadFromGameHelper.cs">
      <Link>Views\EEPK Organiser\Misc\LoadFromGameHelper.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\ViewModel\AssetContainerViewModel.cs">
      <Link>Views\EEPK Organiser\ViewModel\AssetContainerViewModel.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\ViewModel\EcfNodeViewModel.cs">
      <Link>Views\EEPK Organiser\ViewModel\EcfNodeViewModel.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\ViewModel\EffectPartViewModel.cs">
      <Link>Views\EEPK Organiser\ViewModel\EffectPartViewModel.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\ViewModel\EmpKeyframesViewModel.cs">
      <Link>Views\EEPK Organiser\ViewModel\EmpKeyframesViewModel.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\ViewModel\EmpNodeViewModel.cs">
      <Link>Views\EEPK Organiser\ViewModel\EmpNodeViewModel.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\ViewModel\EmpTextureViewModel.cs">
      <Link>Views\EEPK Organiser\ViewModel\EmpTextureViewModel.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\ViewModel\EtrNodeViewModel.cs">
      <Link>Views\EEPK Organiser\ViewModel\EtrNodeViewModel.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\ViewModel\MaterialViewModel.cs">
      <Link>Views\EEPK Organiser\ViewModel\MaterialViewModel.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Controls\ShapeDraw.xaml.cs">
      <Link>Views\EEPK Organiser\View\Controls\ShapeDraw.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EcfEditor.xaml.cs">
      <Link>Views\EEPK Organiser\View\Editors\EcfEditor.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EmpEditor.xaml.cs">
      <Link>Views\EEPK Organiser\View\Editors\EmpEditor.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EMP\EmpKeyframesView.xaml.cs">
      <Link>Views\EEPK Organiser\View\Editors\EMP\EmpKeyframesView.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EMP\EmpKeyframeView.xaml.cs">
      <Link>Views\EEPK Organiser\View\Editors\EMP\EmpKeyframeView.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EMP\EmpModifiersView.xaml.cs">
      <Link>Views\EEPK Organiser\View\Editors\EMP\EmpModifiersView.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EMP\EmpNodeView.xaml.cs">
      <Link>Views\EEPK Organiser\View\Editors\EMP\EmpNodeView.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EMP\EmpTextureView.xaml.cs">
      <Link>Views\EEPK Organiser\View\Editors\EMP\EmpTextureView.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EMP\KeyframedValueView.xaml.cs">
      <Link>Views\EEPK Organiser\View\Editors\EMP\KeyframedValueView.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EtrEditor.xaml.cs">
      <Link>Views\EEPK Organiser\View\Editors\EtrEditor.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Editors\MaterialsEditor.xaml.cs">
      <Link>Views\EEPK Organiser\View\Editors\MaterialsEditor.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Editors\TextureEditor.xaml.cs">
      <Link>Views\EEPK Organiser\View\Editors\TextureEditor.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\EepkEditor.xaml.cs">
      <Link>Views\EEPK Organiser\View\EepkEditor.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Vectors\CustomColor.xaml.cs">
      <Link>Views\EEPK Organiser\View\Vectors\CustomColor.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Vectors\CustomMatUV.xaml.cs">
      <Link>Views\EEPK Organiser\View\Vectors\CustomMatUV.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Vectors\CustomRgbColor.xaml.cs">
      <Link>Views\EEPK Organiser\View\Vectors\CustomRgbColor.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Vectors\CustomVector2.xaml.cs">
      <Link>Views\EEPK Organiser\View\Vectors\CustomVector2.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Vectors\CustomVector3.xaml.cs">
      <Link>Views\EEPK Organiser\View\Vectors\CustomVector3.xaml.cs</Link>
    </Compile>
    <Compile Include="..\..\XV2 Tools\EEPK Editor\View\Vectors\CustomVector4.xaml.cs">
      <Link>Views\EEPK Organiser\View\Vectors\CustomVector4.xaml.cs</Link>
    </Compile>
		
		<Page Include="..\..\XV2 Tools\AudioCueEditor\View\AddCueForm.xaml">
      <Link>Views\ACE\View\AddCueForm.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\AudioCueEditor\View\AddTrackForm.xaml">
      <Link>Views\ACE\View\AddTrackForm.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\AudioCueEditor\View\CueEditorView.xaml">
      <Link>Views\ACE\View\CueEditorView.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\AudioCueEditor\View\EditCueLimit.xaml">
      <Link>Views\ACE\View\EditCueLimit.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\AudioCueEditor\View\EditLoopForm.xaml">
      <Link>Views\ACE\View\EditLoopForm.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\AudioCueEditor\View\EditVolume.xaml">
      <Link>Views\ACE\View\EditVolume.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\AudioCueEditor\View\VolumeControl.xaml">
      <Link>Views\ACE\View\VolumeControl.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\AssetContainerSettings.xaml">
      <Link>Views\EEPK Organiser\Forms\AssetContainerSettings.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\AssetSelector.xaml">
      <Link>Views\EEPK Organiser\Forms\AssetSelector.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\Editors\EcfEditorWindow.xaml">
      <Link>Views\EEPK Organiser\Forms\Editors\EcfEditorWindow.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\Editors\EmbEditForm.xaml">
      <Link>Views\EEPK Organiser\Forms\Editors\EmbEditForm.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\Editors\EmpEditorWindow.xaml">
      <Link>Views\EEPK Organiser\Forms\Editors\EmpEditorWindow.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\Editors\EtrEditorWindow.xaml">
      <Link>Views\EEPK Organiser\Forms\Editors\EtrEditorWindow.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\Editors\MaterialsEditorForm.xaml">
      <Link>Views\EEPK Organiser\Forms\Editors\MaterialsEditorForm.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\EffectSelector.xaml">
      <Link>Views\EEPK Organiser\Forms\EffectSelector.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\EntitySelector.xaml">
      <Link>Views\EEPK Organiser\Forms\EntitySelector.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\KeyframeScale.xaml">
      <Link>Views\EEPK Organiser\Forms\KeyframeScale.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\Recolor\RecolorAll.xaml">
      <Link>Views\EEPK Organiser\Forms\Recolor\RecolorAll.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\Recolor\RecolorTexture.xaml">
      <Link>Views\EEPK Organiser\Forms\Recolor\RecolorTexture.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\Forms\RenameForm.xaml">
      <Link>Views\EEPK Organiser\Forms\RenameForm.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Controls\ShapeDraw.xaml">
      <Link>Views\EEPK Organiser\View\Controls\ShapeDraw.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EcfEditor.xaml">
      <Link>Views\EEPK Organiser\View\Editors\EcfEditor.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EmpEditor.xaml">
      <Link>Views\EEPK Organiser\View\Editors\EmpEditor.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EMP\EmpKeyframesView.xaml">
      <Link>Views\EEPK Organiser\View\Editors\EMP\EmpKeyframesView.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EMP\EmpKeyframeView.xaml">
      <Link>Views\EEPK Organiser\View\Editors\EMP\EmpKeyframeView.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EMP\EmpModifiersView.xaml">
      <Link>Views\EEPK Organiser\View\Editors\EMP\EmpModifiersView.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EMP\EmpNodeView.xaml">
      <Link>Views\EEPK Organiser\View\Editors\EMP\EmpNodeView.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EMP\EmpTextureView.xaml">
      <Link>Views\EEPK Organiser\View\Editors\EMP\EmpTextureView.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EMP\KeyframedValueView.xaml">
      <Link>Views\EEPK Organiser\View\Editors\EMP\KeyframedValueView.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Editors\EtrEditor.xaml">
      <Link>Views\EEPK Organiser\View\Editors\EtrEditor.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Editors\MaterialsEditor.xaml">
      <Link>Views\EEPK Organiser\View\Editors\MaterialsEditor.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Editors\TextureEditor.xaml">
      <Link>Views\EEPK Organiser\View\Editors\TextureEditor.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\EepkEditor.xaml">
      <Link>Views\EEPK Organiser\View\EepkEditor.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Vectors\CustomColor.xaml">
      <Link>Views\EEPK Organiser\View\Vectors\CustomColor.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Vectors\CustomMatUV.xaml">
      <Link>Views\EEPK Organiser\View\Vectors\CustomMatUV.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Vectors\CustomRgbColor.xaml">
      <Link>Views\EEPK Organiser\View\Vectors\CustomRgbColor.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Vectors\CustomVector2.xaml">
      <Link>Views\EEPK Organiser\View\Vectors\CustomVector2.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Vectors\CustomVector3.xaml">
      <Link>Views\EEPK Organiser\View\Vectors\CustomVector3.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="..\..\XV2 Tools\EEPK Editor\View\Vectors\CustomVector4.xaml">
      <Link>Views\EEPK Organiser\View\Vectors\CustomVector4.xaml</Link>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\XV2 Tools\LB_Common\LB_Common.csproj" />
    <ProjectReference Include="..\..\XV2 Tools\Xv2CoreLib\Xv2CoreLib.csproj" />
    <ProjectReference Include="..\MonoGameWpfInterloop\MonoGame.Framework.WpfInterop\MonoGame.Framework.WpfInterop.csproj" />
    <ProjectReference Include="..\MonoGame\MonoGame.Framework\MonoGame.Framework.WindowsDX.csproj" />
  </ItemGroup>
	
	<!-- Copy all required files into build directory -->
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="XCOPY &quot;$(SolutionDir)\RequiredFiles&quot; &quot;$(TargetDir)\XenoKit\&quot; /S /Y" />
  </Target>
	
</Project>