<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFrameworks>net480;net10.0-windows</TargetFrameworks>
    <DefineConstants>WINDOWS;XNADESIGNPROVIDED;STBSHARP_INTERNAL</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
    <Description>The MonoGame runtime for Windows using DirectX API's.</Description>
    <PackageTags>monogame;.net core;core;.net standard;standard;windowsdx</PackageTags>
    <PackageId>MonoGame.Framework.WindowsDX</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**\*" />
    <Compile Remove="obj\**\*" />
    <Compile Remove="Platform\**\*" />
    <Compile Remove="Properties\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Platform\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Platform\GamePlatform.Desktop.cs" />
    <Compile Include="Platform\Graphics\SwapChainRenderTarget.cs" />
    <Compile Include="Platform\Graphics\Texture2D.StbSharp.cs" />
    <Compile Include="Platform\Input\GamePad.XInput.cs" />
    <Compile Include="Platform\Input\InputKeyEventArgs.cs" />
    <Compile Include="Platform\Input\Joystick.Default.cs" />
    <Compile Include="Platform\Input\Keyboard.Windows.cs" />
    <Compile Include="Platform\Input\KeyboardInput.Windows.cs" />
    <Compile Include="Platform\Input\KeysHelper.cs" />
    <Compile Include="Platform\Input\MessageBox.Windows.cs" />
    <Compile Include="Platform\Input\Mouse.Windows.cs" />
    <Compile Include="Platform\Input\MouseCursor.Windows.cs" />

    <Compile Include="Platform\TitleContainer.Desktop.cs" />
    <Compile Include="Platform\Utilities\AssemblyHelper.cs" />
    <Compile Include="Platform\Utilities\CurrentPlatform.cs" />
    <Compile Include="Platform\Utilities\ReflectionHelpers.Legacy.cs" />
    <Compile Include="Platform\Utilities\TimerHelper.cs" />
    <Compile Include="Platform\Windows\HorizontalMouseWheelEventArgs.cs" />
    <Compile Include="Platform\Windows\WinFormsGameForm.cs" />
    <Compile Include="Platform\Windows\WinFormsGamePlatform.cs" />
    <Compile Include="Platform\Windows\WinFormsGameWindow.cs" />
  </ItemGroup> 

  <ItemGroup>
    <Compile Include="..\ThirdParty\StbImageSharp\src\StbImageSharp\**\*.cs" LinkBase="Utilities\StbImageSharp" />
    <Compile Include="..\ThirdParty\StbImageWriteSharp\src\StbImageWriteSharp\**\*.cs" LinkBase="Utilities\StbImageWriteSharp" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="MonoGame.Framework.WindowsDX.targets" PackagePath="build" />
  </ItemGroup>

  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.Jit" Version="2.0.8" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NETStandard.Library" Version="2.0.3" />
    <PackageReference Version="4.2.0" Include="SharpDX" />
    <PackageReference Version="4.2.0" Include="SharpDX.Direct2D1" />
    <PackageReference Version="4.2.0" Include="SharpDX.Direct3D11" />
    <PackageReference Include="SharpDX.Direct3D9" Version="4.2.0" />
    <PackageReference Version="4.2.0" Include="SharpDX.DXGI" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    <PackageReference Version="4.2.0" Include="SharpDX.MediaFoundation" />
    <PackageReference Version="4.2.0" Include="SharpDX.XAudio2" />
    <PackageReference Version="4.2.0" Include="SharpDX.XInput" />
    <PackageReference Include="StbImageSharp" Version="2.27.7" />
    <PackageReference Include="StbImageWriteSharp" Version="1.13.5" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Net.Primitives" Version="4.3.1" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
    <PackageReference Include="System.Runtime" Version="4.3.1" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <Import Project="Platform\DirectX.targets" />
</Project>
